// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbPdcw86jQifUfC9PrpA6Y3MkqJ79zqHQ',
    appId: '1:871434716176:web:34524dcdad064a6f11b695',
    messagingSenderId: '871434716176',
    projectId: 'akib-akfinance',
    authDomain: 'akib-akfinance.firebaseapp.com',
    storageBucket: 'akib-akfinance.appspot.com',
    measurementId: 'G-EB86VSEP08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChewOKiRElmC5EpHOjWPQcpy8FNMa8UMM',
    appId: '1:871434716176:android:2085ebe4e55c78f111b695',
    messagingSenderId: '871434716176',
    projectId: 'akib-akfinance',
    storageBucket: 'akib-akfinance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv2N9kh8KLpFKOQpag3D8-ZLYMN5Nd6hI',
    appId: '1:871434716176:ios:48afe6b5a1db5dd411b695',
    messagingSenderId: '871434716176',
    projectId: 'akib-akfinance',
    storageBucket: 'akib-akfinance.appspot.com',
    iosBundleId: 'com.akib.akfinance',
  );
}
